### ISSUE TITLE
Class not found `com.sun.jna.Callback` (macOS arm)

### ISSUE THREAD

**Issue by mworzala** [eirikb/FleetUI#5]
I switched the target for skiko to `macos-arm64`, but find this error on start. Not sure if I am missing something obvious.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/Callback
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at noria.windowManagement.impl.skiko.themes.MacOSThemeDetector.<init>(MacOSThemeDetector.kt:31)
	at noria.windowManagement.impl.skiko.themes.OsThemeDetector$Companion.createDetector(OsThemeDetector.kt:35)
	at noria.windowManagement.impl.skiko.themes.OsThemeDetector$Companion.access$createDetector(OsThemeDetector.kt:29)
	at noria.windowManagement.impl.skiko.themes.OsThemeDetector$Companion$detector$2.invoke(OsThemeDetector.kt:30)
	at noria.windowManagement.impl.skiko.themes.OsThemeDetector$Companion$detector$2.invoke(OsThemeDetector.kt:30)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at noria.windowManagement.impl.skiko.themes.OsThemeDetector$Companion.getDetector(OsThemeDetector.kt:30)
	at noria.windowManagement.impl.skiko.AwtSkikoWindowManager.<clinit>(AwtSkikoWindowManager.kt:788)
	at fleetui.AppKt.main(App.kt:83)
	at fleetui.AppKt.main(App.kt)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Callback
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 19 more
```

**Comment by eirikb** [comment]
You followed the guide at https://github.com/JetBrains/skiko#using-as-dependency ?

If so it can be a class I've stripped away that I shouldn't have.
I've manually added .jar-files until it worked, and then removed .class files from the "backend-app.jar" until it failed (to make it smaller).  
Only tried building and running on Linux.

**Comment by eirikb** [comment]
Also, did you use Java 17? It's required. I need to add that to the Readme. Preferably JBR 17.

**Comment by mworzala** [comment]
I am using JBR 17 and skiko itself seems fine.  Replacing app.jar with the original does not fix the issue, although copying everything in from `code-cache` does, so I will try to narrow down which one is required.

**Comment by eirikb** [comment]
And welcome to my life the last days :D  
The jar called jna.jar contains that class, and the one called jna-5.11.0(some hash).jar

**Comment by mworzala** [comment]
The following changes make it run, although there are still significant issues (text input does not work being the biggest/most obvious. Could be a macOS permission issue, im not totally sure)

```patch
Index: app/build.gradle.kts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/build.gradle.kts b/app/build.gradle.kts
--- a/app/build.gradle.kts	(revision 0e4a554cc8469f464779bdf64f36f6594f9fbcdd)
+++ b/app/build.gradle.kts	(date 1668432917566)
@@ -10,7 +10,7 @@
 }
 
 val version = "0.7.36"
-val target = "linux-x64"
+val target = "macos-arm64"
 
 java {
     toolchain {
@@ -29,6 +29,9 @@
     implementation("org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.3.3")
     implementation("it.unimi.dsi:fastutil:8.2.1")
 
+    implementation("net.java.dev.jna:jna:5.12.1")
+    implementation("net.java.dev.jna:jna-platform:5.12.1")
+
     implementation(fileTree("lib") {
         include("*.jar")
     })
@@ -41,6 +44,8 @@
         "--add-exports", "java.desktop/sun.java2d=ALL-UNNAMED",
         "--add-exports", "java.desktop/sun.awt=ALL-UNNAMED",
         "--add-opens", "java.desktop/sun.awt.X11=ALL-UNNAMED",
+        "--add-exports", "java.desktop/com.apple.eawt=ALL-UNNAMED",
+        "--add-exports", "java.desktop/sun.lwawt.macosx=ALL-UNNAMED",
     )
     mainClass.set("fleetui.AppKt")
 }
```

**Comment by eirikb** [comment]
Do you want me to just merge that straight in, or do you want to make a PR?

Text input is not working for me either. And animations don't animate. I need to ask JetBrains for help on those. Anything else?

**Comment by mworzala** [comment]
you can merge it. The focus demo doesn't seem to work right although it might be related to the input issue.

**Comment by eirikb** [comment]
Forgot to link the issue with the PR, but it should be fixed now.
Would be nice if we could run some tests in GitHub Actions, but I don't know how. Just a screenshot would be nice.
